language: php

php:
    - "7.4"
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

env:
    global:
        - XDEBUG_MODE=coverage

sudo: false

git:
    submodules: false

before_script:
    - make install check
    - composer update

script:
    - make test
